### author: Sebastian Leifeld

FROM nvcr.io/nvidia/nvhpc:20.11-devel-cuda_multi-ubuntu20.04

RUN apt update
RUN apt install -y make cmake
RUN apt install -y python python-numpy python3 python3-numpy
RUN apt install -y bc libxml2-utils xsltproc tidy vim
